services:
  nextcloud:
    image: nextcloud:stable-fpm-alpine
    container_name: nextcloud-stable-fpm-alpine
    restart: always
    ports:
      - "9000:9000"
    environment:
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_HOST: "${MYSQL_HOST}"
      REDIS_HOST: "${REDIS_HOST}"
    volumes:
      - ./nextcloud_data:/var/www/html
      - "${NEXTCLOUD_USER_DATA_DIR}:/var/www/html/data"
    network_mode: bridge
  nginx:
    image: nginx:alpine-slim
    container_name: nextcloud-nginx
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - nextcloud
    volumes:
      # https://docs.nextcloud.com/server/latest/admin_manual/installation/nginx.html
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nextcloud_data:/var/www/html
      - "${NEXTCLOUD_USER_DATA_DIR}:/var/www/html/data"
    network_mode: bridge
