services:
  portainer:
    image: portainer/portainer-ce:lts
    container_name: portainer-lts
    restart: always
    ports:
      - "9443:9443"
      - "8081:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data
    network_mode: bridge
